title: dozer.nz

description: > 
  My personal infosec website, containing details on vulnerabilities I've found, hacking and 
  reverse engineering writeups, 
  and security advisories for my findings.
  

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dozer.nz" 

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    inline_theme: base16.dark
    wrap: true

# posts dont show up if i date them today in my timezone
future: true

show_excerpts: true

minima:
  skin: dark


plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-include-cache
