title: dozer.nz
description: > 
  My personal infosec website, containing details on vulnerabilities I've found, hacking and 
  reverse engineering writeups, 
  and security advisories for my findings.
  

 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dozer.nz" 

# Build settings
markdown: kramdown
remote_theme: jekyll/minima

show_excerpts: true

minima:
  skin: dark
  social_links:
    twitter: dozernz
    github: dozernz


plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-include-cache
